language: scala
scala:
  - 2.10.5
jdk:
  - oraclejdk8
addons:
    postgresql: "9.3"
    apt:
      packages:
        - haveged
<<<<<<< HEAD
sudo: required
install:
  sbt compile
=======
                          
sudo: required
                          
install:
  sbt compile
>>>>>>> 891db4fa059d8b2aad504b61a883a1561645c889
