language: scala
scala:
  - 2.10.5
jdk:
  - oraclejdk8

sudo: false
                          
install:
  - git clone https://github.com/apache/mahout.git mahout
  - cd mahout
  - git checkout 00a2883ec69b0807a5486c61dfcc7ef27f35ddc6
  - mvn clean install -DskipTests

script:
  sbt compile
